#!/bin/sh

var="3, 5, 5, 7, 5, 7, 5, 5, 3, 5, 5, 9, 7, 3, 3, 5, 5, 5, 7, 3, 5, 5, 3, 3, 5"
res="${var//[^9]}"
echo "$res"
echo "${#res}"

# tr -dc ',' <<<"$var" | awk '{ print length; }'
# tr -dc ',' <<<"$var" | wc -c    #works, but i don't like wc.. ;)
# awk -F, '{print NF-1}' <<<"$var"
# grep -o ',' <<<"$var" | grep -c .
# perl -nle 'print s/,//g' <<<"$var"
