#!/bin/sh
# 1
cd $UNI/os/lab_3
mkdir miliukhin1 miliukhin2
# 2
cd miliukhin1
# 3
cat > oleksandr1
# 4
cp oleksandr1 oleksandr2
cp oleksandr1 oleksandr3
# 5
echo "new string 1" >> oleksandr2
# 6
echo "new string 2
new string 3" >> oleksandr3
# 7.
mv oleksandr2 ../miliukhin2
mv oleksandr3 ../miliukhin2
# 8.
< oleksandr1
# 9
ls -l oleksandr1
# 10
chmod u+x,g+x oleksandr1
# 11
cp oleksandr1 ~/
# 12, 13
mv oleksandr1 oleksandr
# 14, 15
cd .. && rm -r miliukhin1
# 16
cd miliukhin2
# 17
comm --nocheck -1 -2 oleksandr2 oleksandr3 > common_lines
# 18
cat oleksandr2 oleksandr3 > oleksandr
# 19
cd
