-- MySQL Script generated by MySQL Workbench
-- Wed 04 Oct 2023 11:58:03 PM EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`manufacturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`manufacturer` (
  `id` INT NOT NULL,
  `address` INT NOT NULL,
  `phone` INT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`material` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `price` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `manufacturer_id` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_product_manufacturer1_idx` (`manufacturer_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_manufacturer1`
    FOREIGN KEY (`manufacturer_id`)
    REFERENCES `mydb`.`manufacturer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`bowed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bowed` (
  `model_id` INT NOT NULL,
  `size` FLOAT NOT NULL,
  `material_id` INT NULL,
  `product_product_id` INT NOT NULL,
  PRIMARY KEY (`model_id`),
  INDEX `fk_bowed_product1_idx` (`product_product_id` ASC) VISIBLE,
  CONSTRAINT `fk_bowed_product1`
    FOREIGN KEY (`product_product_id`)
    REFERENCES `mydb`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `id` INT NULL DEFAULT CURRENT_TIMESTAMP,
  `fname` VARCHAR(255) NOT NULL,
  `mname` VARCHAR(255) NULL,
  `lname` VARCHAR(255) NOT NULL,
  `salary` FLOAT NULL,
  `position` VARCHAR(45) NULL);


-- -----------------------------------------------------
-- Table `mydb`.`buyer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`buyer` (
  `id` INT NULL DEFAULT CURRENT_TIMESTAMP,
  `fname` VARCHAR(255) NOT NULL,
  `mname` VARCHAR(255) NULL,
  `lname` VARCHAR(255) NOT NULL,
  `salary` VARCHAR(45) NULL);


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `order_number` INT NOT NULL,
  `buyer_id` INT NOT NULL,
  `seller_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`order_number`),
  INDEX `fk_order_buyer1_idx` (`buyer_id` ASC) VISIBLE,
  INDEX `fk_order_employee1_idx` (`seller_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_buyer1`
    FOREIGN KEY (`buyer_id`)
    REFERENCES `mydb`.`buyer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_employee1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `mydb`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`guitar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`guitar` (
  `model_id` INT NOT NULL,
  `scaled_length` FLOAT NULL,
  `length` FLOAT NULL,
  `width` FLOAT NULL,
  `strings` INT NULL,
  `frets` INT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`model_id`),
  INDEX `fk_guitar_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_guitar_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`order_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order_details` (
  `order_details_id` INT NOT NULL,
  `order_number` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity_of_goods` INT NOT NULL,
  PRIMARY KEY (`order_details_id`),
  INDEX `fk_order_details_order1_idx` (`order_number` ASC) VISIBLE,
  INDEX `fk_order_details_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_details_order1`
    FOREIGN KEY (`order_number`)
    REFERENCES `mydb`.`order` (`order_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_details_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`product_has_material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product_has_material` (
  `product_id` INT NOT NULL,
  `material_id` INT NOT NULL,
  `part_name` VARCHAR(45) NULL,
  PRIMARY KEY (`product_id`, `material_id`),
  INDEX `fk_product_has_material_material1_idx` (`material_id` ASC) VISIBLE,
  INDEX `fk_product_has_material_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_has_material_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_material_material1`
    FOREIGN KEY (`material_id`)
    REFERENCES `mydb`.`material` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
