---
output:
   pdf_document:
     latex_engine: xelatex
header-includes:
- \setmainfont{Nimbus Roman}
- \setmonofont[Scale=MatchLowercase]{Nimbus Roman}
title: Галина Іванівна
bibliography: /home/sasha/Documents/bibliography.bib
---

Сігма Алгебри

```{r}
2^13*9
```

проводим експеримент $n$ разів,
$m$ --- кільки разів подія, тоді частота --- $\omega=\frac{m}{n}$

$$
\nu=\lim_{k\to\infty}\omega_k
$$

невизначеність результатів і стійкість відносних частот

елементарні події
: нерозкладні результати випробування (тобто останні, не можна сказати АБО)

$\Omega$ --- множина елементарних подій $\omega$

- $\Omega={1;2;3;4;5;6}$ --- для гральної кісточки
- $\Omega={\text{усі точки відрізка, на який кидають точку}}$

Підмножини простору елементарних подій називають
**подіями** і позначають $A, B, C$

Подія $\bar A$ --- протилежна до $A$
парне --- непарне

$$
\Omega/A: \\
\bar A = \{\omega|\omega \in A\}
$$

1. сума подій (або А, або Б) --- $A \cup B$
2. Сумісні ше шось там де нема тих шо повторюється
3. Суміщення подій $C=A \cap B = A \cdot B$ (відбулась і A і B)
4. Різниця: $A\\B=A \cap \bar B$
5. Еквівалентні події (не рівні!) Якщо кожна відбудеться тільки, якщо відбулась інша.
6. Несумісні мда не відбулися $A \cap B = \emptyset$

## Повна група подій

- попарно несумісні $(A_i A_j = \emptyset, (i\neq j, i,j=\overline{1,n}),$
- одна з них обов'язково відбудеться $A_1 + A_2 + ... + A_n = \Omega$
A = {3,4}, B={2,5}, C={1,6} не сумісні але будь-яка з них мяу.

## Сприятливі події

Повна група сприятливих подій --- несумісних попарно, їх
об'єднання еквівалентне події $A$.

- попарно несумісні $(A_i * A_j = \emptyset, (i\neq j, i,j=\overline{1,n}),$
- одна з них обов'язково відбудеться $A_1 + A_2 + ... + A_n = A$

Випало два то випало парне число

# Найпростіша тема --- повторення незалежних послідовних випробувань

A

p=P(A)

q=1-p=1-p

закон розподілу функції двох випадкових величин не треба
